// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common/ledger.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common {

  /// <summary>Holder for reflection information generated from common/ledger.proto</summary>
  public static partial class LedgerReflection {

    #region Descriptor
    /// <summary>File descriptor for common/ledger.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LedgerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNjb21tb24vbGVkZ2VyLnByb3RvEgZjb21tb24imwEKDkJsb2NrY2hhaW5J",
            "bmZvEg4KBmhlaWdodBgBIAEoBBIYChBjdXJyZW50QmxvY2tIYXNoGAIgASgM",
            "EhkKEXByZXZpb3VzQmxvY2tIYXNoGAMgASgMEkQKGWJvb3RzdHJhcHBpbmdT",
            "bmFwc2hvdEluZm8YBCABKAsyIS5jb21tb24uQm9vdHN0cmFwcGluZ1NuYXBz",
            "aG90SW5mbyI4ChlCb290c3RyYXBwaW5nU25hcHNob3RJbmZvEhsKE2xhc3RC",
            "bG9ja0luU25hcHNob3QYASABKARCVgokb3JnLmh5cGVybGVkZ2VyLmZhYnJp",
            "Yy5wcm90b3MuY29tbW9uWi5naXRodWIuY29tL2h5cGVybGVkZ2VyL2ZhYnJp",
            "Yy1wcm90b3MtZ28vY29tbW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.BlockchainInfo), global::Common.BlockchainInfo.Parser, new[]{ "Height", "CurrentBlockHash", "PreviousBlockHash", "BootstrappingSnapshotInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.BootstrappingSnapshotInfo), global::Common.BootstrappingSnapshotInfo.Parser, new[]{ "LastBlockInSnapshot" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Contains information about the blockchain ledger such as height, current
  /// block hash, and previous block hash.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BlockchainInfo : pb::IMessage<BlockchainInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BlockchainInfo> _parser = new pb::MessageParser<BlockchainInfo>(() => new BlockchainInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BlockchainInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.LedgerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlockchainInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlockchainInfo(BlockchainInfo other) : this() {
      height_ = other.height_;
      currentBlockHash_ = other.currentBlockHash_;
      previousBlockHash_ = other.previousBlockHash_;
      bootstrappingSnapshotInfo_ = other.bootstrappingSnapshotInfo_ != null ? other.bootstrappingSnapshotInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlockchainInfo Clone() {
      return new BlockchainInfo(this);
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 1;
    private ulong height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "currentBlockHash" field.</summary>
    public const int CurrentBlockHashFieldNumber = 2;
    private pb::ByteString currentBlockHash_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString CurrentBlockHash {
      get { return currentBlockHash_; }
      set {
        currentBlockHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "previousBlockHash" field.</summary>
    public const int PreviousBlockHashFieldNumber = 3;
    private pb::ByteString previousBlockHash_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString PreviousBlockHash {
      get { return previousBlockHash_; }
      set {
        previousBlockHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bootstrappingSnapshotInfo" field.</summary>
    public const int BootstrappingSnapshotInfoFieldNumber = 4;
    private global::Common.BootstrappingSnapshotInfo bootstrappingSnapshotInfo_;
    /// <summary>
    /// Specifies bootstrapping snapshot info if the channel is bootstrapped from a snapshot.
    /// It is nil if the channel is not bootstrapped from a snapshot.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Common.BootstrappingSnapshotInfo BootstrappingSnapshotInfo {
      get { return bootstrappingSnapshotInfo_; }
      set {
        bootstrappingSnapshotInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BlockchainInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BlockchainInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Height != other.Height) return false;
      if (CurrentBlockHash != other.CurrentBlockHash) return false;
      if (PreviousBlockHash != other.PreviousBlockHash) return false;
      if (!object.Equals(BootstrappingSnapshotInfo, other.BootstrappingSnapshotInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Height != 0UL) hash ^= Height.GetHashCode();
      if (CurrentBlockHash.Length != 0) hash ^= CurrentBlockHash.GetHashCode();
      if (PreviousBlockHash.Length != 0) hash ^= PreviousBlockHash.GetHashCode();
      if (bootstrappingSnapshotInfo_ != null) hash ^= BootstrappingSnapshotInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Height != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Height);
      }
      if (CurrentBlockHash.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(CurrentBlockHash);
      }
      if (PreviousBlockHash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(PreviousBlockHash);
      }
      if (bootstrappingSnapshotInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BootstrappingSnapshotInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Height != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Height);
      }
      if (CurrentBlockHash.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(CurrentBlockHash);
      }
      if (PreviousBlockHash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(PreviousBlockHash);
      }
      if (bootstrappingSnapshotInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BootstrappingSnapshotInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Height != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Height);
      }
      if (CurrentBlockHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CurrentBlockHash);
      }
      if (PreviousBlockHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PreviousBlockHash);
      }
      if (bootstrappingSnapshotInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BootstrappingSnapshotInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BlockchainInfo other) {
      if (other == null) {
        return;
      }
      if (other.Height != 0UL) {
        Height = other.Height;
      }
      if (other.CurrentBlockHash.Length != 0) {
        CurrentBlockHash = other.CurrentBlockHash;
      }
      if (other.PreviousBlockHash.Length != 0) {
        PreviousBlockHash = other.PreviousBlockHash;
      }
      if (other.bootstrappingSnapshotInfo_ != null) {
        if (bootstrappingSnapshotInfo_ == null) {
          BootstrappingSnapshotInfo = new global::Common.BootstrappingSnapshotInfo();
        }
        BootstrappingSnapshotInfo.MergeFrom(other.BootstrappingSnapshotInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Height = input.ReadUInt64();
            break;
          }
          case 18: {
            CurrentBlockHash = input.ReadBytes();
            break;
          }
          case 26: {
            PreviousBlockHash = input.ReadBytes();
            break;
          }
          case 34: {
            if (bootstrappingSnapshotInfo_ == null) {
              BootstrappingSnapshotInfo = new global::Common.BootstrappingSnapshotInfo();
            }
            input.ReadMessage(BootstrappingSnapshotInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Height = input.ReadUInt64();
            break;
          }
          case 18: {
            CurrentBlockHash = input.ReadBytes();
            break;
          }
          case 26: {
            PreviousBlockHash = input.ReadBytes();
            break;
          }
          case 34: {
            if (bootstrappingSnapshotInfo_ == null) {
              BootstrappingSnapshotInfo = new global::Common.BootstrappingSnapshotInfo();
            }
            input.ReadMessage(BootstrappingSnapshotInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Contains information for the bootstrapping snapshot.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BootstrappingSnapshotInfo : pb::IMessage<BootstrappingSnapshotInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BootstrappingSnapshotInfo> _parser = new pb::MessageParser<BootstrappingSnapshotInfo>(() => new BootstrappingSnapshotInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BootstrappingSnapshotInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.LedgerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BootstrappingSnapshotInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BootstrappingSnapshotInfo(BootstrappingSnapshotInfo other) : this() {
      lastBlockInSnapshot_ = other.lastBlockInSnapshot_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BootstrappingSnapshotInfo Clone() {
      return new BootstrappingSnapshotInfo(this);
    }

    /// <summary>Field number for the "lastBlockInSnapshot" field.</summary>
    public const int LastBlockInSnapshotFieldNumber = 1;
    private ulong lastBlockInSnapshot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong LastBlockInSnapshot {
      get { return lastBlockInSnapshot_; }
      set {
        lastBlockInSnapshot_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BootstrappingSnapshotInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BootstrappingSnapshotInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LastBlockInSnapshot != other.LastBlockInSnapshot) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LastBlockInSnapshot != 0UL) hash ^= LastBlockInSnapshot.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LastBlockInSnapshot != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(LastBlockInSnapshot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LastBlockInSnapshot != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(LastBlockInSnapshot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LastBlockInSnapshot != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LastBlockInSnapshot);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BootstrappingSnapshotInfo other) {
      if (other == null) {
        return;
      }
      if (other.LastBlockInSnapshot != 0UL) {
        LastBlockInSnapshot = other.LastBlockInSnapshot;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LastBlockInSnapshot = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LastBlockInSnapshot = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
