// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msp/msp_principal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common {

  /// <summary>Holder for reflection information generated from msp/msp_principal.proto</summary>
  public static partial class MspPrincipalReflection {

    #region Descriptor
    /// <summary>File descriptor for msp/msp_principal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MspPrincipalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdtc3AvbXNwX3ByaW5jaXBhbC5wcm90bxIGY29tbW9uIsYBCgxNU1BQcmlu",
            "Y2lwYWwSRQoYcHJpbmNpcGFsX2NsYXNzaWZpY2F0aW9uGAEgASgOMiMuY29t",
            "bW9uLk1TUFByaW5jaXBhbC5DbGFzc2lmaWNhdGlvbhIRCglwcmluY2lwYWwY",
            "AiABKAwiXAoOQ2xhc3NpZmljYXRpb24SCAoEUk9MRRAAEhUKEU9SR0FOSVpB",
            "VElPTl9VTklUEAESDAoISURFTlRJVFkQAhINCglBTk9OWU1JVFkQAxIMCghD",
            "T01CSU5FRBAEInEKEE9yZ2FuaXphdGlvblVuaXQSFgoObXNwX2lkZW50aWZp",
            "ZXIYASABKAkSJgoeb3JnYW5pemF0aW9uYWxfdW5pdF9pZGVudGlmaWVyGAIg",
            "ASgJEh0KFWNlcnRpZmllcnNfaWRlbnRpZmllchgDIAEoDCKVAQoHTVNQUm9s",
            "ZRIWCg5tc3BfaWRlbnRpZmllchgBIAEoCRIpCgRyb2xlGAIgASgOMhsuY29t",
            "bW9uLk1TUFJvbGUuTVNQUm9sZVR5cGUiRwoLTVNQUm9sZVR5cGUSCgoGTUVN",
            "QkVSEAASCQoFQURNSU4QARIKCgZDTElFTlQQAhIICgRQRUVSEAMSCwoHT1JE",
            "RVJFUhAEIp0BChRNU1BJZGVudGl0eUFub255bWl0eRJNCg5hbm9ueW1pdHlf",
            "dHlwZRgBIAEoDjI1LmNvbW1vbi5NU1BJZGVudGl0eUFub255bWl0eS5NU1BJ",
            "ZGVudGl0eUFub255bWl0eVR5cGUiNgoYTVNQSWRlbnRpdHlBbm9ueW1pdHlU",
            "eXBlEgsKB05PTUlOQUwQABINCglBTk9OWU1PVVMQASI9ChFDb21iaW5lZFBy",
            "aW5jaXBhbBIoCgpwcmluY2lwYWxzGAEgAygLMhQuY29tbW9uLk1TUFByaW5j",
            "aXBhbEJTCiRvcmcuaHlwZXJsZWRnZXIuZmFicmljLnByb3Rvcy5jb21tb25a",
            "K2dpdGh1Yi5jb20vaHlwZXJsZWRnZXIvZmFicmljLXByb3Rvcy1nby9tc3Bi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.MSPPrincipal), global::Common.MSPPrincipal.Parser, new[]{ "PrincipalClassification", "Principal" }, null, new[]{ typeof(global::Common.MSPPrincipal.Types.Classification) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.OrganizationUnit), global::Common.OrganizationUnit.Parser, new[]{ "MspIdentifier", "OrganizationalUnitIdentifier", "CertifiersIdentifier" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.MSPRole), global::Common.MSPRole.Parser, new[]{ "MspIdentifier", "Role" }, null, new[]{ typeof(global::Common.MSPRole.Types.MSPRoleType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.MSPIdentityAnonymity), global::Common.MSPIdentityAnonymity.Parser, new[]{ "AnonymityType" }, null, new[]{ typeof(global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.CombinedPrincipal), global::Common.CombinedPrincipal.Parser, new[]{ "Principals" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// MSPPrincipal aims to represent an MSP-centric set of identities.
  /// In particular, this structure allows for definition of
  ///  - a group of identities that are member of the same MSP
  ///  - a group of identities that are member of the same organization unit
  ///    in the same MSP
  ///  - a group of identities that are administering a specific MSP
  ///  - a specific identity
  /// Expressing these groups is done given two fields of the fields below
  ///  - Classification, that defines the type of classification of identities
  ///    in an MSP this principal would be defined on; Classification can take
  ///    three values:
  ///     (i)  ByMSPRole: that represents a classification of identities within
  ///          MSP based on one of the two pre-defined MSP rules, "member" and "admin"
  ///     (ii) ByOrganizationUnit: that represents a classification of identities
  ///          within MSP based on the organization unit an identity belongs to
  ///     (iii)ByIdentity that denotes that MSPPrincipal is mapped to a single
  ///          identity/certificate; this would mean that the Principal bytes
  ///          message
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MSPPrincipal : pb::IMessage<MSPPrincipal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MSPPrincipal> _parser = new pb::MessageParser<MSPPrincipal>(() => new MSPPrincipal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MSPPrincipal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.MspPrincipalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MSPPrincipal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MSPPrincipal(MSPPrincipal other) : this() {
      principalClassification_ = other.principalClassification_;
      principal_ = other.principal_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MSPPrincipal Clone() {
      return new MSPPrincipal(this);
    }

    /// <summary>Field number for the "principal_classification" field.</summary>
    public const int PrincipalClassificationFieldNumber = 1;
    private global::Common.MSPPrincipal.Types.Classification principalClassification_ = global::Common.MSPPrincipal.Types.Classification.Role;
    /// <summary>
    /// Classification describes the way that one should process
    /// Principal. An Classification value of "ByOrganizationUnit" reflects
    /// that "Principal" contains the name of an organization this MSP
    /// handles. A Classification value "ByIdentity" means that
    /// "Principal" contains a specific identity. Default value
    /// denotes that Principal contains one of the groups by
    /// default supported by all MSPs ("admin" or "member").
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Common.MSPPrincipal.Types.Classification PrincipalClassification {
      get { return principalClassification_; }
      set {
        principalClassification_ = value;
      }
    }

    /// <summary>Field number for the "principal" field.</summary>
    public const int PrincipalFieldNumber = 2;
    private pb::ByteString principal_ = pb::ByteString.Empty;
    /// <summary>
    /// Principal completes the policy principal definition. For the default
    /// principal types, Principal can be either "Admin" or "Member".
    /// For the ByOrganizationUnit/ByIdentity values of Classification,
    /// PolicyPrincipal acquires its value from an organization unit or
    /// identity, respectively.
    /// For the Combined Classification type, the Principal is a marshalled
    /// CombinedPrincipal.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Principal {
      get { return principal_; }
      set {
        principal_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MSPPrincipal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MSPPrincipal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PrincipalClassification != other.PrincipalClassification) return false;
      if (Principal != other.Principal) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PrincipalClassification != global::Common.MSPPrincipal.Types.Classification.Role) hash ^= PrincipalClassification.GetHashCode();
      if (Principal.Length != 0) hash ^= Principal.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PrincipalClassification != global::Common.MSPPrincipal.Types.Classification.Role) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PrincipalClassification);
      }
      if (Principal.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Principal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PrincipalClassification != global::Common.MSPPrincipal.Types.Classification.Role) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PrincipalClassification);
      }
      if (Principal.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Principal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PrincipalClassification != global::Common.MSPPrincipal.Types.Classification.Role) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PrincipalClassification);
      }
      if (Principal.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Principal);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MSPPrincipal other) {
      if (other == null) {
        return;
      }
      if (other.PrincipalClassification != global::Common.MSPPrincipal.Types.Classification.Role) {
        PrincipalClassification = other.PrincipalClassification;
      }
      if (other.Principal.Length != 0) {
        Principal = other.Principal;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PrincipalClassification = (global::Common.MSPPrincipal.Types.Classification) input.ReadEnum();
            break;
          }
          case 18: {
            Principal = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PrincipalClassification = (global::Common.MSPPrincipal.Types.Classification) input.ReadEnum();
            break;
          }
          case 18: {
            Principal = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MSPPrincipal message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Classification {
        /// <summary>
        /// Represents the one of the dedicated MSP roles, the
        /// </summary>
        [pbr::OriginalName("ROLE")] Role = 0,
        /// <summary>
        /// one of a member of MSP network, and the one of an
        /// administrator of an MSP network
        /// </summary>
        [pbr::OriginalName("ORGANIZATION_UNIT")] OrganizationUnit = 1,
        /// <summary>
        /// groupping of entities, per MSP affiliation
        /// E.g., this can well be represented by an MSP's
        /// Organization unit
        /// </summary>
        [pbr::OriginalName("IDENTITY")] Identity = 2,
        /// <summary>
        /// identity
        /// </summary>
        [pbr::OriginalName("ANONYMITY")] Anonymity = 3,
        /// <summary>
        /// an identity to be anonymous or nominal.
        /// </summary>
        [pbr::OriginalName("COMBINED")] Combined = 4,
      }

    }
    #endregion

  }

  /// <summary>
  /// OrganizationUnit governs the organization of the Principal
  /// field of a policy principal when a specific organization unity members
  /// are to be defined within a policy principal.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OrganizationUnit : pb::IMessage<OrganizationUnit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrganizationUnit> _parser = new pb::MessageParser<OrganizationUnit>(() => new OrganizationUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrganizationUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.MspPrincipalReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationUnit(OrganizationUnit other) : this() {
      mspIdentifier_ = other.mspIdentifier_;
      organizationalUnitIdentifier_ = other.organizationalUnitIdentifier_;
      certifiersIdentifier_ = other.certifiersIdentifier_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationUnit Clone() {
      return new OrganizationUnit(this);
    }

    /// <summary>Field number for the "msp_identifier" field.</summary>
    public const int MspIdentifierFieldNumber = 1;
    private string mspIdentifier_ = "";
    /// <summary>
    /// MSPIdentifier represents the identifier of the MSP this organization unit
    /// refers to
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MspIdentifier {
      get { return mspIdentifier_; }
      set {
        mspIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "organizational_unit_identifier" field.</summary>
    public const int OrganizationalUnitIdentifierFieldNumber = 2;
    private string organizationalUnitIdentifier_ = "";
    /// <summary>
    /// OrganizationUnitIdentifier defines the organizational unit under the
    /// MSP identified with MSPIdentifier
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationalUnitIdentifier {
      get { return organizationalUnitIdentifier_; }
      set {
        organizationalUnitIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "certifiers_identifier" field.</summary>
    public const int CertifiersIdentifierFieldNumber = 3;
    private pb::ByteString certifiersIdentifier_ = pb::ByteString.Empty;
    /// <summary>
    /// CertifiersIdentifier is the hash of certificates chain of trust
    /// related to this organizational unit
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString CertifiersIdentifier {
      get { return certifiersIdentifier_; }
      set {
        certifiersIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrganizationUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrganizationUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MspIdentifier != other.MspIdentifier) return false;
      if (OrganizationalUnitIdentifier != other.OrganizationalUnitIdentifier) return false;
      if (CertifiersIdentifier != other.CertifiersIdentifier) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MspIdentifier.Length != 0) hash ^= MspIdentifier.GetHashCode();
      if (OrganizationalUnitIdentifier.Length != 0) hash ^= OrganizationalUnitIdentifier.GetHashCode();
      if (CertifiersIdentifier.Length != 0) hash ^= CertifiersIdentifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MspIdentifier.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MspIdentifier);
      }
      if (OrganizationalUnitIdentifier.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OrganizationalUnitIdentifier);
      }
      if (CertifiersIdentifier.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(CertifiersIdentifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MspIdentifier.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MspIdentifier);
      }
      if (OrganizationalUnitIdentifier.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OrganizationalUnitIdentifier);
      }
      if (CertifiersIdentifier.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(CertifiersIdentifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MspIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MspIdentifier);
      }
      if (OrganizationalUnitIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationalUnitIdentifier);
      }
      if (CertifiersIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CertifiersIdentifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrganizationUnit other) {
      if (other == null) {
        return;
      }
      if (other.MspIdentifier.Length != 0) {
        MspIdentifier = other.MspIdentifier;
      }
      if (other.OrganizationalUnitIdentifier.Length != 0) {
        OrganizationalUnitIdentifier = other.OrganizationalUnitIdentifier;
      }
      if (other.CertifiersIdentifier.Length != 0) {
        CertifiersIdentifier = other.CertifiersIdentifier;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MspIdentifier = input.ReadString();
            break;
          }
          case 18: {
            OrganizationalUnitIdentifier = input.ReadString();
            break;
          }
          case 26: {
            CertifiersIdentifier = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MspIdentifier = input.ReadString();
            break;
          }
          case 18: {
            OrganizationalUnitIdentifier = input.ReadString();
            break;
          }
          case 26: {
            CertifiersIdentifier = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MSPRole governs the organization of the Principal
  /// field of an MSPPrincipal when it aims to define one of the
  /// two dedicated roles within an MSP: Admin and Members.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MSPRole : pb::IMessage<MSPRole>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MSPRole> _parser = new pb::MessageParser<MSPRole>(() => new MSPRole());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MSPRole> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.MspPrincipalReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MSPRole() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MSPRole(MSPRole other) : this() {
      mspIdentifier_ = other.mspIdentifier_;
      role_ = other.role_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MSPRole Clone() {
      return new MSPRole(this);
    }

    /// <summary>Field number for the "msp_identifier" field.</summary>
    public const int MspIdentifierFieldNumber = 1;
    private string mspIdentifier_ = "";
    /// <summary>
    /// MSPIdentifier represents the identifier of the MSP this principal
    /// refers to
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MspIdentifier {
      get { return mspIdentifier_; }
      set {
        mspIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "role" field.</summary>
    public const int RoleFieldNumber = 2;
    private global::Common.MSPRole.Types.MSPRoleType role_ = global::Common.MSPRole.Types.MSPRoleType.Member;
    /// <summary>
    /// MSPRoleType defines which of the available, pre-defined MSP-roles
    /// an identiy should posess inside the MSP with identifier MSPidentifier
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Common.MSPRole.Types.MSPRoleType Role {
      get { return role_; }
      set {
        role_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MSPRole);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MSPRole other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MspIdentifier != other.MspIdentifier) return false;
      if (Role != other.Role) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MspIdentifier.Length != 0) hash ^= MspIdentifier.GetHashCode();
      if (Role != global::Common.MSPRole.Types.MSPRoleType.Member) hash ^= Role.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MspIdentifier.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MspIdentifier);
      }
      if (Role != global::Common.MSPRole.Types.MSPRoleType.Member) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Role);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MspIdentifier.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MspIdentifier);
      }
      if (Role != global::Common.MSPRole.Types.MSPRoleType.Member) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Role);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MspIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MspIdentifier);
      }
      if (Role != global::Common.MSPRole.Types.MSPRoleType.Member) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Role);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MSPRole other) {
      if (other == null) {
        return;
      }
      if (other.MspIdentifier.Length != 0) {
        MspIdentifier = other.MspIdentifier;
      }
      if (other.Role != global::Common.MSPRole.Types.MSPRoleType.Member) {
        Role = other.Role;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MspIdentifier = input.ReadString();
            break;
          }
          case 16: {
            Role = (global::Common.MSPRole.Types.MSPRoleType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MspIdentifier = input.ReadString();
            break;
          }
          case 16: {
            Role = (global::Common.MSPRole.Types.MSPRoleType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MSPRole message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum MSPRoleType {
        /// <summary>
        /// Represents an MSP Member
        /// </summary>
        [pbr::OriginalName("MEMBER")] Member = 0,
        /// <summary>
        /// Represents an MSP Admin
        /// </summary>
        [pbr::OriginalName("ADMIN")] Admin = 1,
        /// <summary>
        /// Represents an MSP Client
        /// </summary>
        [pbr::OriginalName("CLIENT")] Client = 2,
        /// <summary>
        /// Represents an MSP Peer
        /// </summary>
        [pbr::OriginalName("PEER")] Peer = 3,
        /// <summary>
        /// Represents an MSP Orderer
        /// </summary>
        [pbr::OriginalName("ORDERER")] Orderer = 4,
      }

    }
    #endregion

  }

  /// <summary>
  /// MSPIdentityAnonymity can be used to enforce an identity to be anonymous or nominal.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MSPIdentityAnonymity : pb::IMessage<MSPIdentityAnonymity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MSPIdentityAnonymity> _parser = new pb::MessageParser<MSPIdentityAnonymity>(() => new MSPIdentityAnonymity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MSPIdentityAnonymity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.MspPrincipalReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MSPIdentityAnonymity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MSPIdentityAnonymity(MSPIdentityAnonymity other) : this() {
      anonymityType_ = other.anonymityType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MSPIdentityAnonymity Clone() {
      return new MSPIdentityAnonymity(this);
    }

    /// <summary>Field number for the "anonymity_type" field.</summary>
    public const int AnonymityTypeFieldNumber = 1;
    private global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType anonymityType_ = global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType.Nominal;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType AnonymityType {
      get { return anonymityType_; }
      set {
        anonymityType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MSPIdentityAnonymity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MSPIdentityAnonymity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AnonymityType != other.AnonymityType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AnonymityType != global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType.Nominal) hash ^= AnonymityType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AnonymityType != global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType.Nominal) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AnonymityType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AnonymityType != global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType.Nominal) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AnonymityType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AnonymityType != global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType.Nominal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AnonymityType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MSPIdentityAnonymity other) {
      if (other == null) {
        return;
      }
      if (other.AnonymityType != global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType.Nominal) {
        AnonymityType = other.AnonymityType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AnonymityType = (global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AnonymityType = (global::Common.MSPIdentityAnonymity.Types.MSPIdentityAnonymityType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MSPIdentityAnonymity message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum MSPIdentityAnonymityType {
        /// <summary>
        /// Represents a nominal MSP Identity
        /// </summary>
        [pbr::OriginalName("NOMINAL")] Nominal = 0,
        /// <summary>
        /// Represents an anonymous MSP Identity
        /// </summary>
        [pbr::OriginalName("ANONYMOUS")] Anonymous = 1,
      }

    }
    #endregion

  }

  /// <summary>
  /// CombinedPrincipal governs the organization of the Principal
  /// field of a policy principal when principal_classification has
  /// indicated that a combined form of principals is required
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CombinedPrincipal : pb::IMessage<CombinedPrincipal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CombinedPrincipal> _parser = new pb::MessageParser<CombinedPrincipal>(() => new CombinedPrincipal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CombinedPrincipal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.MspPrincipalReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombinedPrincipal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombinedPrincipal(CombinedPrincipal other) : this() {
      principals_ = other.principals_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombinedPrincipal Clone() {
      return new CombinedPrincipal(this);
    }

    /// <summary>Field number for the "principals" field.</summary>
    public const int PrincipalsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Common.MSPPrincipal> _repeated_principals_codec
        = pb::FieldCodec.ForMessage(10, global::Common.MSPPrincipal.Parser);
    private readonly pbc::RepeatedField<global::Common.MSPPrincipal> principals_ = new pbc::RepeatedField<global::Common.MSPPrincipal>();
    /// <summary>
    /// Principals refer to combined principals
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Common.MSPPrincipal> Principals {
      get { return principals_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CombinedPrincipal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CombinedPrincipal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!principals_.Equals(other.principals_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= principals_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      principals_.WriteTo(output, _repeated_principals_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      principals_.WriteTo(ref output, _repeated_principals_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += principals_.CalculateSize(_repeated_principals_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CombinedPrincipal other) {
      if (other == null) {
        return;
      }
      principals_.Add(other.principals_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            principals_.AddEntriesFrom(input, _repeated_principals_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            principals_.AddEntriesFrom(ref input, _repeated_principals_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
