// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: peer/peer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from peer/peer.proto</summary>
  public static partial class PeerReflection {

    #region Descriptor
    /// <summary>File descriptor for peer/peer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PeerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9wZWVyL3BlZXIucHJvdG8SBnByb3RvcxoTcGVlci9wcm9wb3NhbC5wcm90",
            "bxoccGVlci9wcm9wb3NhbF9yZXNwb25zZS5wcm90bzJPCghFbmRvcnNlchJD",
            "Cg9Qcm9jZXNzUHJvcG9zYWwSFi5wcm90b3MuU2lnbmVkUHJvcG9zYWwaGC5w",
            "cm90b3MuUHJvcG9zYWxSZXNwb25zZUJSCiJvcmcuaHlwZXJsZWRnZXIuZmFi",
            "cmljLnByb3Rvcy5wZWVyWixnaXRodWIuY29tL2h5cGVybGVkZ2VyL2ZhYnJp",
            "Yy1wcm90b3MtZ28vcGVlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protos.ProposalReflection.Descriptor, global::Protos.ProposalResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
